# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_auto_20160106_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_1',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
