# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0003_auto_20160106_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_2',
        ),
        migrations.DeleteModel(
            name='Data_3',
        ),
        migrations.DeleteModel(
            name='Data_4',
        ),
        migrations.AlterField(
            model_name='data_1',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
