# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0005_data_2_data_3_data_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='data_3',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='data_4',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
