# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0008_data_2_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2',
            name='robot',
            field=models.IntegerField(default=2),
        ),
    ]
