# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Robot1',
            new_name='Robot_1',
        ),
    ]
