# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20160113_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot_1',
            old_name='dat',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='robot_1',
            old_name='stat',
            new_name='state',
        ),
    ]
