# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_second'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Now_time1',
            new_name='Now_time_1',
        ),
        migrations.RenameModel(
            old_name='Second',
            new_name='Second_1',
        ),
    ]
