# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20160114_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Second_1',
            new_name='Now_time_11',
        ),
        migrations.RenameModel(
            old_name='Robot_1',
            new_name='Robot_11',
        ),
        migrations.RenameModel(
            old_name='Now_time_1',
            new_name='Second_11',
        ),
        migrations.RenameField(
            model_name='now_time_11',
            old_name='sec',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='second_11',
            old_name='time',
            new_name='sec',
        ),
    ]
