# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20160115_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Now_time_11',
            new_name='Now_time_1',
        ),
        migrations.RenameModel(
            old_name='Robot_11',
            new_name='Robot_1',
        ),
        migrations.RenameModel(
            old_name='Second_11',
            new_name='Second_1',
        ),
    ]
