# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20160115_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Now_time_1',
        ),
        migrations.DeleteModel(
            name='Robot_1',
        ),
        migrations.DeleteModel(
            name='Second_1',
        ),
    ]
