# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_de',
            name='order_id',
        ),
    ]
