# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_remove_order_de_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_de',
            name='order_sn',
            field=models.CharField(max_length=40),
        ),
    ]
