# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_auto_20160125_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_de',
            name='order_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Order'),
        ),
    ]
