# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_auto_20160125_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebody',
            name='goods_station',
            field=models.CharField(default='', max_length=40),
        ),
    ]
