# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0005_linebody_goods_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linebody',
            name='goods_station',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_station',
            field=models.CharField(default='', max_length=40),
        ),
    ]
