# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0006_auto_20160128_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('error_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=40)),
                ('error_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mark_state', models.CharField(default='0', max_length=30)),
                ('next_main', models.CharField(default='', max_length=30)),
                ('next_fu', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
