# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0007_error_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_mark',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='test2.Mark'),
        ),
    ]
