# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_car_car_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='next_fu',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
