# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0010_auto_20160204_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='next_fu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextf', to='test2.Mark'),
        ),
    ]
