# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0011_auto_20160204_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_de',
            name='goods_count',
            field=models.IntegerField(default=''),
        ),
    ]
