# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='email',
        ),
    ]
