# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0002_remove_mydata_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mydata',
            new_name='Mydata1',
        ),
    ]
