# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b1', '0003_auto_20160115_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mydata1',
        ),
    ]
