# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b1', '0004_delete_mydata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
