# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160219_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='default_mark',
            field=models.CharField(default='', max_length=40),
        ),
    ]
