# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_de_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_de',
            name='order_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ORD', to='app1.Order'),
        ),
    ]
