# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160219_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_de',
            name='order_sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Order'),
        ),
    ]
