# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20160222_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='distination',
            field=models.CharField(default='', max_length=40),
        ),
    ]
