# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_car_distination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='distination',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
