# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_order_different_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='different_car',
        ),
    ]
