# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_order_different_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['mark_id']},
        ),
    ]
