# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20160302_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebody',
            name='line_error',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
