# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_linebody_line_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ensure_code',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
