# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160219_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='next_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextm', to='app1.Mark'),
        ),
    ]
