# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20160222_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=40)),
                ('order_time', models.CharField(max_length=40)),
                ('order_state', models.CharField(default='未完成', max_length=40)),
                ('finish_time', models.CharField(blank=True, default='', max_length=40)),
                ('total_time', models.CharField(blank=True, default='', max_length=40)),
                ('work_type', models.CharField(blank=True, default='', max_length=40)),
                ('car_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Car')),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Linebody')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPcb_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_count', models.IntegerField(default='')),
                ('order_state', models.CharField(default='0', max_length=40)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Goods')),
                ('order_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Order')),
            ],
        ),
    ]
