# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20160225_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_mark',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
