# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20160225_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_mark',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
