# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
