# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='sta_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_number',
            field=models.CharField(max_length=40),
        ),
    ]
