# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20160118_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='linebody',
            old_name='line_name',
            new_name='material_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='left_ci',
            new_name='line_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='right_ci',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='station_number',
            new_name='order_time',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_sign',
        ),
        migrations.AddField(
            model_name='linebody',
            name='station_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='linebody',
            name='line_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='material',
            name='mat_count',
            field=models.IntegerField(default=''),
        ),
    ]
