# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20160119_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='mat_name',
            new_name='mat_number',
        ),
    ]
