# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20160119_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mat_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
