# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_material_mat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(default='', max_length=40),
        ),
    ]
