# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_order_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linebody',
            old_name='station_name',
            new_name='station_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(default='未完成', max_length=40),
        ),
    ]
