# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_auto_20160119_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebody',
            name='material_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Material'),
        ),
        migrations.AlterField(
            model_name='order',
            name='line_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Linebody'),
        ),
    ]
