# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_order_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='test1.Car'),
        ),
    ]
