# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_auto_20160120_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_number',
        ),
    ]
