# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0014_remove_order_car_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_number',
            new_name='car_name',
        ),
        migrations.AddField(
            model_name='order',
            name='car_name',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='test1.Car'),
        ),
    ]
