# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0020_auto_20160120_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_time',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
