# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0021_order_finish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='down_time',
        ),
        migrations.AddField(
            model_name='order',
            name='down_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
