# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0022_auto_20160120_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linebody',
            name='id',
        ),
        migrations.AlterField(
            model_name='linebody',
            name='line_number',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
