# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0023_auto_20160121_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='mat_number',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='sta_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
