# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0024_auto_20160121_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_number', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='linebody',
            name='station_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Station'),
        ),
    ]
