# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0026_linebody_wuliao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebody',
            name='wuliao_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
