# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shuzi',
            field=models.IntegerField(default=0),
        ),
    ]
