# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(choices=[('a', 'achar'), ('s', 'sakura'), ('l', 'love')], max_length=100),
        ),
    ]
