# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0004_auto_20160105_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('wife', models.CharField(blank=True, max_length=20)),
                ('girl', models.AutoField(primary_key=True, serialize=False)),
                ('say', models.CharField(max_length=22, verbose_name='这是我说的')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='num',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='per',
            field=models.ManyToManyField(to='app7.Person', verbose_name='Person外键'),
        ),
    ]
