# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0005_auto_20160105_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='per',
        ),
    ]
