# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0006_remove_test_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='person',
            field=models.ManyToManyField(to='app7.Author'),
        ),
        migrations.AlterField(
            model_name='test',
            name='wife',
            field=models.CharField(max_length=20),
        ),
    ]
