# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0007_auto_20160105_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='person',
        ),
        migrations.AddField(
            model_name='test',
            name='person',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app7.Author'),
        ),
    ]
