# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0008_auto_20160105_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app7.Author'),
        ),
    ]
