# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0009_auto_20160105_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='person',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app7.Author'),
        ),
    ]
