# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0012_auto_20160105_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='girl',
            new_name='id',
        ),
    ]
